name: flutter_online_shop
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  retrofit: ^4.1.0
  logger: ^2.1.0
  flutter_bloc: ^8.1.4
  bloc_test: ^9.1.6
  test: ^1.24.3
  mocktail: ^1.0.3
  modal_progress_hud_nsn: ^0.4.0

  
  
  
 




 

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.7
  flutter_gen: ^5.4.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  flutter_gen_runner: ^5.4.0
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1
  retrofit_generator: ^8.1.0
  

flutter_native_splash:
 color: "#f5c9be"
 image: assets/images/logo.png
 ios: true
 android: true

flutter_icons: 
 ios: true
 android: true
 image_path: assets/images/icon.png
 color: "#efdaa1" 

flutter:

  uses-material-design: true

  assets:
    - assets/images/




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
